### ISSUE TITLE
Session->execute  parameter $options should be optional

### ISSUE THREAD

**Issue by ylin0603** [SachaMorard/cassandra-stubs#2]
version 1.3.1

maybe add an default null value? $options=null

**Comment by SachaMorard** [comment]
Hello
Sorry but if your IDE is working correctly, we don't need to add null value to optional parameter because annotations are working great for that.
https://github.com/SachaMorard/cassandra-stubs/blob/master/Library/Cassandra/Session.php#L44-L45
